### ISSUE TITLE
3 armor shards missing on U1M2

### ISSUE THREAD

**Issue by Joca64** [m-x-d/Mission64-data#1]
You forgot to add 3 armor shards to the left of the lift after dropping from the pipe.
Also, great job on nailing the look of the original. I had recently started doing the same thing and ended up remaking the first 4 maps with QuArK, but your version looks much nicer. You can find my maps here: https://www.quaddicted.com/forum/viewtopic.php?id=422

I'm not a pro mapper or anything, only ever used the QuArK editor, but if you think I could be of some assistance give me a shout.

Keep up the good work.

**Comment by m-x-d** [comment]
Seems to be fixed now.
